listCirconscription = ['Avalon', 'Bonavista--Exploits', 'Humber--St. Barbe--Baie Verte',
       'Labrador', "Random--Burin--St. George's",
       "St. John's North/St. John's-Nord",
       "St. John's South/St. John's-Sud", 'Cardigan', 'Charlottetown',
       'Egmont', 'Malpeque', 'Cape Breton--Canso',
       'Central Nova/Nova-Centre', 'Dartmouth--Cole Harbour', 'Halifax',
       'Halifax West/Halifax-Ouest', 'Kings--Hants',
       'North Nova/Nova-Nord', 'Sackville--Eastern Shore',
       "South Shore--St. Margaret's", 'Sydney--Victoria',
       'West Nova/Nova-Ouest', 'Acadie--Bathurst', 'Beauséjour',
       'Fredericton', 'Fundy', 'Madawaska--Restigouche', 'Miramichi',
       'Moncton--Riverview--Dieppe', 'St. Croix--Belleisle', 'Saint John',
       'Tobique--Mactaquac', 'Abitibi--Témiscamingue', 'Ahuntsic',
       'Alfred-Pellan', 'Argenteuil--Mirabel', 'Beauce',
       'Beauharnois--Salaberry', 'Beauport', 'Berthier--Maskinongé',
       'Bourassa', 'Brome--Missisquoi', 'Brossard--La Prairie',
       'Chambly--Borduas', 'Charlesbourg', 'Charlevoix--Montmorency',
       'Châteauguay--Saint-Constant', 'Chicoutimi--Le Fjord',
       'Compton--Stanstead', 'Drummond', 'Gaspésie--Îles-de-la-Madeleine',
       'Gatineau', 'Hochelaga', 'Honoré-Mercier', 'Hull--Aylmer',
       'Jeanne-Le Ber', 'Joliette', 'Jonquière--Alma', 'Lac-Saint-Louis',
       "La Pointe-de-l'Île", 'LaSalle--Émard', 'Laurentides--Labelle',
       'Laurier', 'Laval', 'Laval--Les Îles', 'Lévis--Bellechasse',
       'Longueuil', 'Lotbinière--Chutes-de-la-Chaudière', 'Louis-Hébert',
       'Louis-Saint-Laurent', 'Manicouagan', 'Marc-Aurèle-Fortin',
       'Matapédia--Matane', "Mégantic--L'Érable", 'Montcalm',
       'Mount Royal/Mont-Royal', 'Notre-Dame-de-Grâce--Lachine',
       'Nunavik--Eeyou', 'Outremont', 'Papineau', 'Pierrefonds--Dollard',
       'Pontiac', 'Portneuf', 'Québec', 'Repentigny', 'Richelieu',
       'Richmond--Arthabaska', 'Rimouski--Témiscouata',
       'Rivière-des-Mille-Îles', 'Rivière-du-Loup--Montmagny',
       'Rivière-du-Nord', 'Roberval', 'Rosemont--La Petite-Patrie',
       'Saint-Bruno--Saint-Hubert', 'Saint-Hyacinthe--Bagot',
       'Saint-Jean', 'Saint-Lambert', 'Saint-Laurent--Cartierville',
       'Saint-Léonard--Saint-Michel', 'Saint-Maurice--Champlain',
       'Shefford', 'Sherbrooke', 'Terrebonne--Blainville',
       'Trois-Rivières', 'Vaudreuil-Soulanges',
       'Verchères--Les Patriotes', 'Westmount--Ville-Marie',
       'Ajax--Pickering', 'Algoma--Manitoulin--Kapuskasing',
       'Ancaster--Dundas--Flamborough--Westdale', 'Barrie',
       'Beaches--East York', 'Bramalea--Gore--Malton',
       'Brampton--Springdale', 'Brampton West/Brampton-Ouest', 'Brant',
       'Burlington', 'Cambridge', 'Carleton--Lanark',
       'Chatham-Kent--Essex', 'Clarington--Scugog--Uxbridge', 'Davenport',
       'Don Valley East/Don Valley-Est',
       'Don Valley West/Don Valley-Ouest', 'Dufferin--Caledon',
       'Eglinton--Lawrence', 'Elgin--Middlesex--London', 'Essex',
       'Etobicoke Centre/Etobicoke-Centre', 'Etobicoke--Lakeshore',
       'Etobicoke North/Etobicoke-Nord', 'Glengarry--Prescott--Russell',
       'Grey--Bruce--Owen Sound', 'Guelph', 'Haldimand--Norfolk',
       'Haliburton--Kawartha Lakes--Brock', 'Halton',
       'Hamilton Centre/Hamilton-Centre',
       'Hamilton East--Stoney Creek/Hamilton-Est--Stoney Creek',
       'Hamilton Mountain', 'Huron--Bruce', 'Kenora',
       'Kingston and the Islands/Kingston et les Îles',
       'Kitchener Centre/Kitchener-Centre', 'Kitchener--Conestoga',
       'Kitchener--Waterloo', 'Lanark--Frontenac--Lennox and Addington',
       'Leeds--Grenville', 'London--Fanshawe',
       'London North Centre/London-Centre-Nord',
       'London West/London-Ouest', 'Markham--Unionville',
       'Middlesex--Kent--Lambton',
       'Mississauga--Brampton South/Mississauga--Brampton-Sud',
       'Mississauga East--Cooksville/Mississauga-Est--Cooksville',
       'Mississauga--Erindale', 'Mississauga South/Mississauga-Sud',
       'Mississauga--Streetsville', 'Nepean--Carleton',
       'Newmarket--Aurora', 'Niagara Falls',
       'Niagara West--Glanbrook/Niagara-Ouest--Glanbrook', 'Nickel Belt',
       'Nipissing--Timiskaming', 'Northumberland--Quinte West',
       'Oak Ridges--Markham', 'Oakville', 'Oshawa',
       'Ottawa Centre/Ottawa-Centre', 'Ottawa--Orléans',
       'Ottawa South/Ottawa-Sud', 'Ottawa--Vanier',
       'Ottawa West--Nepean/Ottawa-Ouest--Nepean', 'Oxford',
       'Parkdale--High Park', 'Parry Sound--Muskoka', 'Perth--Wellington',
       'Peterborough',
       'Pickering--Scarborough East/Pickering--Scarborough-Est',
       'Prince Edward--Hastings', 'Renfrew--Nipissing--Pembroke',
       'Richmond Hill', 'St. Catharines', "St. Paul's", 'Sarnia--Lambton',
       'Sault Ste. Marie', 'Scarborough--Agincourt',
       'Scarborough Centre/Scarborough-Centre', 'Scarborough--Guildwood',
       'Scarborough--Rouge River',
       'Scarborough Southwest/Scarborough-Sud-Ouest', 'Simcoe--Grey',
       'Simcoe North/Simcoe-Nord', 'Stormont--Dundas--South Glengarry',
       'Sudbury', 'Thornhill', 'Thunder Bay--Rainy River',
       'Thunder Bay--Superior North/Thunder Bay--Superior-Nord',
       'Timmins--James Bay/Timmins--Baie James',
       'Toronto Centre/Toronto-Centre', 'Toronto--Danforth',
       'Trinity--Spadina', 'Vaughan', 'Welland',
       'Wellington--Halton Hills', 'Whitby--Oshawa', 'Willowdale',
       'Windsor--Tecumseh', 'Windsor West/Windsor-Ouest',
       'York Centre/York-Centre', 'York--Simcoe',
       'York South--Weston/York-Sud--Weston', 'York West/York-Ouest',
       'Brandon--Souris', 'Charleswood--St. James', 'Churchill',
       'Dauphin--Swan River', 'Elmwood--Transcona', 'Kildonan--St. Paul',
       'Portage--Lisgar', 'Provencher', 'Saint Boniface/Saint-Boniface',
       'Selkirk--Interlake', 'Winnipeg Centre/Winnipeg-Centre',
       'Winnipeg North/Winnipeg-Nord', 'Winnipeg South/Winnipeg-Sud',
       'Winnipeg South Centre/Winnipeg-Centre-Sud',
       'Battlefords--Lloydminster', 'Blackstrap',
       'Churchill River/Rivière Churchill', 'Cypress Hills--Grasslands',
       'Palliser', 'Prince Albert', 'Regina--Lumsden--Lake Centre',
       "Regina--Qu'Appelle", 'Saskatoon--Humboldt',
       'Saskatoon--Rosetown--Biggar', 'Saskatoon--Wanuskewin',
       'Souris--Moose Mountain', 'Wascana', 'Yorkton--Melville',
       'Athabasca', 'Calgary East/Calgary-Est',
       'Calgary North Centre/Calgary-Centre-Nord',
       'Calgary Northeast/Calgary-Nord-Est', 'Calgary--Nose Hill',
       'Calgary South Centre/Calgary-Centre-Sud',
       'Calgary Southeast/Calgary-Sud-Est',
       'Calgary Southwest/Calgary-Sud-Ouest',
       'Calgary West/Calgary-Ouest', 'Crowfoot', 'Edmonton--Beaumont',
       'Edmonton Centre/Edmonton-Centre', 'Edmonton East/Edmonton-Est',
       'Edmonton--Leduc', 'Edmonton--St. Albert',
       'Edmonton--Sherwood Park', 'Edmonton--Spruce Grove',
       'Edmonton--Strathcona', 'Lethbridge', 'Macleod', 'Medicine Hat',
       'Peace River', 'Red Deer', 'Vegreville--Wainwright',
       'Westlock--St. Paul', 'Wetaskiwin', 'Wild Rose', 'Yellowhead',
       'Abbotsford', 'Burnaby--Douglas', 'Burnaby--New Westminster',
       'Cariboo--Prince George', 'Chilliwack--Fraser Canyon',
       'Delta--Richmond East/Delta--Richmond-Est', 'Dewdney--Alouette',
       'Esquimalt--Juan de Fuca', 'Fleetwood--Port Kells',
       'Kamloops--Thompson', 'Kelowna', 'Kootenay--Columbia', 'Langley',
       'Nanaimo--Alberni', 'Nanaimo--Cowichan',
       'Newton--North Delta/Newton--Delta-Nord',
       'New Westminster--Coquitlam',
       'North Okanagan--Shuswap/Okanagan-Nord--Shuswap',
       'North Vancouver', 'Okanagan--Coquihalla',
       'Port Moody--Westwood--Port Coquitlam',
       'Prince George--Peace River', 'Richmond', 'Saanich--Gulf Islands',
       'Skeena--Bulkley Valley', 'Southern Interior',
       'South Surrey--White Rock--Cloverdale/Surrey-Sud--White Rock--Cloverdale',
       'Surrey North/Surrey-Nord', 'Vancouver Centre/Vancouver-Centre',
       'Vancouver East/Vancouver-Est',
       'Vancouver Island North/Île de Vancouver-Nord',
       'Vancouver Kingsway', 'Vancouver Quadra',
       'Vancouver South/Vancouver-Sud', 'Victoria',
       'West Vancouver--Sunshine Coast', 'Yukon', 'Western Arctic',
       'Nunavut', 'Bonavista--Gander--Grand Falls--Windsor',
       "St. John's East/St. John's-Est",
       "St. John's South--Mount Pearl/St. John's-Sud--Mount Pearl",
       'Cumberland--Colchester--Musquodoboit Valley', 'Fundy Royal',
       'New Brunswick Southwest/Nouveau-Brunswick-Sud-Ouest',
       'Abitibi--Baie-James--Nunavik--Eeyou',
       'Argenteuil--Papineau--Mirabel',
       'Bas-Richelieu--Nicolet--Bécancour', 'Beauport--Limoilou',
       'Charlesbourg--Haute-Saint-Charles',
       'Haute-Gaspésie--La Mitis--Matane--Matapédia',
       'Laurier--Sainte-Marie', 'Longueuil--Pierre-Boucher',
       "Montmagny--L'Islet--Kamouraska--Rivière-du-Loup",
       'Montmorency--Charlevoix--Haute-Côte-Nord',
       'Portneuf--Jacques-Cartier',
       'Rimouski-Neigette--Témiscouata--Les Basques',
       'Roberval--Lac-Saint-Jean', 'Bruce--Grey--Owen Sound',
       'Carleton--Mississippi Mills', 'Durham',
       'Lambton--Kent--Middlesex', 'Charleswood--St. James--Assiniboia',
       'Dauphin--Swan River--Marquette',
       'Desnethé--Missinippi--Churchill River/Desnethé--Missinippi--Rivière Churchill',
       'Calgary Centre/Calgary-Centre',
       'Calgary Centre-North/Calgary-Centre-Nord',
       'Edmonton--Mill Woods--Beaumont', 'Fort McMurray--Athabasca',
       'British Columbia Southern Interior/Colombie-Britannique-Southern Interior',
       'Kamloops--Thompson--Cariboo', 'Kelowna--Lake Country',
       'Okanagan--Shuswap', 'Pitt Meadows--Maple Ridge--Mission',
       'West Vancouver--Sunshine Coast--Sea to Sky Country',
       'Bonavista--Burin--Trinity', 'Coast of Bays--Central--Notre Dame',
       'Long Range Mountains', 'Cumberland--Colchester',
       'Sackville--Preston--Chezzetcook', 'South Shore--St. Margarets',
       'Miramichi--Grand Lake', 'Saint John--Rothesay',
       'Ahuntsic-Cartierville', 'Argenteuil--La Petite-Nation',
       'Avignon--La Mitis--Matane--Matapédia',
       "Beauport--Côte-de-Beaupré--Île d'Orléans--Charlevoix",
       'Bécancour--Nicolet--Saurel', 'Bellechasse--Les Etchemins--Lévis',
       'Beloeil--Chambly', 'Brossard--Saint-Lambert',
       'Châteauguay--Lacolle', 'Dorval--Lachine--LaSalle',
       'Gaspésie--Les Îles-de-la-Madeleine', 'Jonquière', 'La Prairie',
       'Lac-Saint-Jean', 'LaSalle--Émard--Verdun', 'Lévis--Lotbinière',
       'Longueuil--Charles-LeMoyne', 'Longueuil--Saint-Hubert', 'Mirabel',
       'Montarville', 'Notre-Dame-de-Grâce--Westmount',
       'Pierre-Boucher--Les Patriotes--Verchères', 'Saint-Laurent',
       'Salaberry--Suroît', 'Terrebonne', 'Thérèse-De Blainville',
       'Vaudreuil--Soulanges',
       'Ville-Marie--Le Sud-Ouest--Île-des-Soeurs', 'Vimy', 'Ajax',
       'Aurora--Oak Ridges--Richmond Hill', 'Barrie--Innisfil',
       'Barrie--Springwater--Oro-Medonte', 'Bay of Quinte/Baie de Quinte',
       'Brampton Centre/Brampton-Centre', 'Brampton East/Brampton-Est',
       'Brampton North/Brampton-Nord', 'Brampton South/Brampton-Sud',
       'Brantford--Brant', 'Carleton', 'Chatham-Kent--Leamington',
       'Don Valley North/Don Valley-Nord', 'Flamborough--Glanbrook',
       'Hamilton West--Ancaster--Dundas/Hamilton-Ouest--Ancaster--Dundas',
       'Hastings--Lennox and Addington', 'Humber River--Black Creek',
       'Kanata--Carleton', 'King--Vaughan',
       'Kitchener South--Hespeler/Kitchener-Sud--Hespeler',
       'Lanark--Frontenac--Kingston',
       'Leeds--Grenville--Thousand Islands and Rideau Lakes/Leeds--Grenville--Thousand Islands et Rideau Lakes',
       'Markham--Stouffville', 'Markham--Thornhill', 'Milton',
       'Mississauga Centre/Mississauga-Centre', 'Mississauga--Erin Mills',
       'Mississauga--Lakeshore', 'Mississauga--Malton', 'Nepean',
       'Niagara Centre/Niagara-Centre', 'Niagara West/Niagara-Ouest',
       'Northumberland--Peterborough South/Northumberland--Peterborough-Sud',
       'Oakville North--Burlington/Oakville-Nord--Burlington', 'Orléans',
       'Peterborough--Kawartha', 'Pickering--Uxbridge',
       'Scarborough North/Scarborough-Nord', 'Scarborough--Rouge Park',
       'Spadina--Fort York',
       'Thunder Bay--Superior North/Thunder Bay--Supérieur-Nord',
       "Toronto--St. Paul's", 'University--Rosedale',
       'Vaughan--Woodbridge', 'Waterloo', 'Whitby',
       'Charleswood--St. James--Assiniboia--Headingley',
       'Churchill--Keewatinook Aski', 'Dauphin--Swan River--Neepawa',
       'Saint Boniface--Saint Vital/Saint-Boniface--Saint-Vital',
       'Selkirk--Interlake--Eastman',
       'Carlton Trail--Eagle Creek/Sentier Carlton--Eagle Creek',
       'Moose Jaw--Lake Centre--Lanigan', 'Regina--Lewvan',
       'Regina--Wascana', 'Saskatoon West/Saskatoon-Ouest',
       'Saskatoon--Grasswood', 'Saskatoon--University', 'Banff--Airdrie',
       'Battle River--Crowfoot', 'Bow River', 'Calgary Confederation',
       'Calgary Forest Lawn', 'Calgary Heritage', 'Calgary Midnapore',
       'Calgary Nose Hill', 'Calgary Rocky Ridge', 'Calgary Shepard',
       'Calgary Signal Hill', 'Calgary Skyview', 'Edmonton Griesbach',
       'Edmonton Manning', 'Edmonton Mill Woods', 'Edmonton Riverbend',
       'Edmonton Strathcona', 'Edmonton West/Edmonton-Ouest',
       'Edmonton--Wetaskiwin', 'Foothills', 'Fort McMurray--Cold Lake',
       'Grande Prairie--Mackenzie', 'Lakeland',
       'Medicine Hat--Cardston--Warner', 'Peace River--Westlock',
       'Red Deer--Lacombe', 'Red Deer--Mountain View',
       'St. Albert--Edmonton', 'Sherwood Park--Fort Saskatchewan',
       'Sturgeon River--Parkland',
       'Burnaby North--Seymour/Burnaby-Nord--Seymour',
       'Burnaby South/Burnaby-Sud',
       'Central Okanagan--Similkameen--Nicola', 'Chilliwack--Hope',
       'Cloverdale--Langley City', 'Coquitlam--Port Coquitlam',
       'Courtenay--Alberni', 'Cowichan--Malahat--Langford', 'Delta',
       'Esquimalt--Saanich--Sooke', 'Langley--Aldergrove',
       'Mission--Matsqui--Fraser Canyon', 'Nanaimo--Ladysmith',
       'New Westminster--Burnaby', 'North Island--Powell River',
       'North Okanagan--Shuswap', 'Pitt Meadows--Maple Ridge',
       'Port Moody--Coquitlam',
       'Prince George--Peace River--Northern Rockies',
       'Richmond Centre/Richmond-Centre',
       'South Okanagan--West Kootenay/Okanagan-Sud--Kootenay-Ouest',
       'South Surrey--White Rock/Surrey-Sud--White Rock',
       'Steveston--Richmond East/Steveston--Richmond-Est',
       'Surrey Centre/Surrey-Centre', 'Surrey--Newton',
       'Vancouver Granville',
       'Northwest Territories/Territoires du Nord-Ouest']